### ISSUE TITLE
Adding XBRLUS enviroment key within R

### ISSUE THREAD

**Issue by SteveBronder** [bergant/xbrlus#1]
Just wanted to note that you can use 

Sys.setenv(XBRLUS_API_KEY = YOUR_API_KEY)

to create a new environment variable instead of finding home and adding a .Renviron

**Comment by bergant** [comment]
Yes, for interactive experimenting with the package this is enough. But when programming (and that is why APIs exist) you could accidentally disclose your key when sharing the code. 
Usually user home is not accessible to other users.
I find it convenient to store the key in .Renviron even when using it only interactively, because every new session will have this key already set. 

See also http://blog.revolutionanalytics.com/2015/11/how-to-store-and-use-authentication-details-with-r.html

**Comment by SteveBronder** [comment]
This is very reasonable, thank you for clearing this up!
